---
- hosts: all
  tasks:
    - name: Check for failed login attempts
      shell: grep "Failed password" /var/log/auth.log 2>/dev/null || grep "Failed password" /var/log/secure 2>/dev/null || echo "Log not found"

    - name: Check for open SSH sessions
      shell: who | grep -i ssh

    - name: List all SUID files
      shell: find /usr/bin -perm -4000 -type f -exec ls -la {} \; 2>/dev/null | head -5

    - name: Check for listening ports
      shell: netstat -tuln || ss -tuln

    - name: Check firewall status
      shell: ufw status || firewall-cmd --state || pfctl -s info || echo "No firewall found"

    - name: Check for suspicious processes
      shell: ps aux | grep -E '(bash|ksh|sh|tcsh|csh|zsh|perl|python|ruby|php|java|nc|netcat)' | grep -v grep | head -5